service: buttonize-plugin-example

plugins:
  - "../src/index"
  # - serverless-plugin-buttonize

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-central-1

custom:
  buttonize:
    apiKey: abc

functions:
  hello:
    handler: handler.hello
    events:
      - buttonize:
          path: users/create
          method: get
